### ISSUE TITLE
Reduce Lag

### ISSUE THREAD

**Issue by Pro245Mc** [amalon/hoganfam-trains#5]
Hi, I love your work. Tell me, the trains lag a lot because of the entities. Is it possible to reduce the lag ? The blue train is the worst concerning lag. Would love that, because it sad for such a great train to have so much lag. Thanks

**Comment by amalon** [comment]
Thanks. Yeh lag can certainly be an issue. The TrainCarts wiki has [a page about lag](https://wiki.traincarts.net/p/TrainCarts/Lag) that might help. Some of those things can be modified in the yml file quite easily.

I'd be interested what sort of lag in particular you are seeing. I.e. it could be server lag (resulting in TPS drop and juddery train movement but otherwise smooth looking around), network lag (i suppose feels like server lag but without TPS drop), or client lag (juddery to even look around).

There are a lot of entities. Each slice of the train is one (and the metro trains are made up of 5 slices per carriage), each door is one, each set of seats is one, possibly each place where you can sit (though they don't show up without the resource pack so maybe not them), and each piece of platform on which you can walk, and thats like 3x15+4=49 shulkers per carriage (for metro train), plus 1 for each bogie.

Ideas are certainly welcome for reducing lag.

**Comment by Pro245Mc** [comment]
Thanks for the reply. Yes it's typically "looking around lag". I'm no programmer, but what if you made a "light" version? 
Of cours that means sacrificing aesthetics, but most people don't need to use tons of seats or walk around all the carrages.
We just want something useful that look cool for small mp servers.
Could you remove some of the things you spoke about and make it so than only one carrage can be used (say 5 seats), and the other carrage doors stay closed ? That way the train looks cool (on the outside) and lag is reduced, but that way we can use the working carrage and choose the light version or the main version..... :)

**Comment by Pro245Mc** [comment]
And that way, you have 2 versions, so your artistic work isn't lost. 2 versions of each train makes it usable for all. :)

**Comment by amalon** [comment]
That would be fairly easy to do, since the saved train module is built out of parts, I could have multiple versions built in without the resource pack even changing. E.g. have a peak at srv/class158/class158.yml.in, I could add more options for enabling/disabling seats / platform skulkers, then have a few preset configurations, and it'd be trivial if anybody to build a custom configuration too.

I'll have a play around and get you a sample yml file to try to see if it helps with the lag.

**Comment by Pro245Mc** [comment]
Wow thanks, that would be amazing. I just want to say, I've been using the resource pack for a year, and we love your work. I often check back for updates, and encourage you to keep at it. The day you release this, people using the traincart plugin will love it, and i'm sure the développer will help you publicise it on there spigot page If you ask. It's unique, and there is nothing like it out there. 

Your work brings minecraft to life, thanks so much.

**Comment by amalon** [comment]
I've added a _lite.yml version to the last release. The only change is the removal of platforms. For class158 this seems to reduce the number of entities reported by minecraft for a single train by around 280, down to about 50. Removing the invisible seat positions doesn't reduce entities, I think its all server side, but removing the visible seating would drop it by another 18. The seats could potentially be combined into the body of the train, but it would mean a fair bit of duplication unless I can make a way to merge models automatically.

Can you give it a try and comment on whether that reduces the lag to more acceptable levels for you?

**Comment by Pro245Mc** [comment]
Hi Amalon,
That's such great news. Ok, I'm going to test it now and I'll let yo know about the lag .

**Comment by Pro245Mc** [comment]
Yes, so I gained around 15fps. I guess it counts.
this sounds like an interesting idea: "The seats could potentially be combined into the body of the train".
I'm guessing that means a bit of time. Anything you can do would be great for quality of life. Thanks again
